"use client";
import "./globals.css";
import "./my.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  let content;
  switch (pathname) {
    case "/":
      content = (
        <ul className="login-menu">
          <li>
            <h4>home navbar</h4>
          </li>
          <li>
            <Link href="/login">login page</Link>
          </li>
          <li>
            <Link href="/about">about page</Link>
          </li>
        </ul>
      );
      break;

      content = (
        <ul className="login-menu">
          <li>
            <h4>login menu</h4>
          </li>
          <li>
            <Link href="/login">login main</Link>
          </li>
          <li>
            <Link href="/login/studentlogin">student main</Link>
          </li>
          <li>
            <Link href="/login/collegelogin">college main</Link>
          </li>
        </ul>
      );
      break;
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        {content}
        {/* <ul className="login-menu">
          <li>
            <h4>home menu</h4>
          </li>
          <li>
            <Link href="/login">login page</Link>
          </li>
          <li>
            <Link href="/about">college page</Link>
          </li>
        </ul> */}
        {children}
      </body>
    </html>
  );
}
